version: 2
source:
  - name: public
    schema: public
    table: 
      - name: RawData
models:
  - name: medical_data_transformed
    description: "A transformed version of the medical data"
    columns:
      - name: channel_title
        description: "The title or channel name of the telegram channel"
        tests:
          - not_null
      - name: message
        description: "The message that is scraped from the channel mentioned"
        tests:
          - not_null
      - name: date
        description: "The time when the message was posted"
        tests:
          - not_null
